#!/usr/bin/env python3
"""Generate the colour scheme worn by devices without dynamic colour (Android 8-11).

Material 3's tonal-spot algorithm, the same one the platform runs on a wallpaper from
Android 12 on, applied to a fixed seed: the launcher icon's green, imported from the
generator that paints it so a re-coloured icon cannot leave this behind. Output is a
Kotlin file of plain colour constants, so the app carries no colour library and every
value is readable in review.

The generator is not part of the build. It needs Google's material-color-utilities,
which is not a dependency of this project:

    uv venv /tmp/mcu && VIRTUAL_ENV=/tmp/mcu uv pip install materialyoucolor
    /tmp/mcu/bin/python tools/generate_scheme.py

Re-run it only to change the seed or the spec, and edit them here rather than the
generated file. What the scheme is *for* is stated where a reader meets the decision,
in ui/theme/Theme.kt.
"""

from pathlib import Path

from materialyoucolor.dynamiccolor.material_dynamic_colors import MaterialDynamicColors
from materialyoucolor.hct import Hct
from materialyoucolor.scheme.scheme_tonal_spot import SchemeTonalSpot

from generate_icon import BG_INNER

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "app/src/main/java/io/github/valeronm/breadcrumb/ui/theme/SeededScheme.kt"

# The launcher icon's background gradient starts here — the app's one stated colour.
SEED = 0xFF000000 | int(BG_INNER.lstrip("#"), 16)

# Pinned rather than left on the library's default: this scheme stands in for the one the
# platform generates from a wallpaper on Android 12 and up, and that one is the 2021 spec.
# Generating the fallback to a later spec would make the same app two apps across the era
# line — tinted on-colours here, white ones there — against the very schemes every colour
# decision in this app was judged on.
SPEC = "2021"

# Every role Compose's ColorScheme takes, in its own declaration order. A role missing here
# keeps the library's baseline default on the builds this scheme exists to dress, which is
# why SeededSchemeTest holds the list against the class rather than trusting this comment.
ROLES = [
    "primary", "onPrimary", "primaryContainer", "onPrimaryContainer",
    "inversePrimary",
    "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
    "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
    "background", "onBackground",
    "surface", "onSurface", "surfaceVariant", "onSurfaceVariant", "surfaceTint",
    "inverseSurface", "inverseOnSurface",
    "error", "onError", "errorContainer", "onErrorContainer",
    "outline", "outlineVariant", "scrim",
    "surfaceBright", "surfaceDim",
    "surfaceContainer", "surfaceContainerHigh", "surfaceContainerHighest",
    "surfaceContainerLow", "surfaceContainerLowest",
    "primaryFixed", "primaryFixedDim", "onPrimaryFixed", "onPrimaryFixedVariant",
    "secondaryFixed", "secondaryFixedDim", "onSecondaryFixed", "onSecondaryFixedVariant",
    "tertiaryFixed", "tertiaryFixedDim", "onTertiaryFixed", "onTertiaryFixedVariant",
]


def kotlin_scheme(dark: bool) -> str:
    name, builder = ("SeededDarkScheme", "darkColorScheme") if dark else ("SeededLightScheme", "lightColorScheme")
    scheme = SchemeTonalSpot(Hct.from_int(SEED), dark, 0.0, spec_version=SPEC)
    lines = [f"internal val {name} = {builder}("]
    for role in ROLES:
        lines.append(f"    {role} = Color(0x{getattr(MaterialDynamicColors, role).get_argb(scheme):08X}),")
    lines.append(")")
    return "\n".join(lines)


OUT.write_text(f"""// Generated by tools/generate_scheme.py from seed #{SEED & 0xFFFFFF:06X} — edit parameters there, not here.
package io.github.valeronm.breadcrumb.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

{kotlin_scheme(dark=False)}

{kotlin_scheme(dark=True)}
""")
print(f"wrote {OUT.relative_to(REPO)}")
